### ISSUE TITLE
Factorio 0.15

### ISSUE THREAD

**Issue by j2ghz** [MrP123/TimeLapseMod#4]
Are there any plans for 0.15 compatibility?

**Comment by Arcanum417** [comment]
no

**Comment by MrP123** [comment]
I'm currently very busy, so I'm not sure whether I'm going to update the mod (the latest release is for Factorio 0.12) any time soon.
If you'd like to update it yourself, just send a pull request.

Otherwise there are a couple of other time lapse mods that basically do the same thing.

**Comment by j2ghz** [comment]
Found one: https://mods.factorio.com/mods/credomane/CredoTimeLapseMod

**Comment by MrP123** [comment]
Just for completion's sake:
I finally had the time to update the mod to Factorio version 0.15
